### ISSUE TITLE
Ukol 12

### ISSUE THREAD

**Issue by Sunriseee** [Sunriseee/python_kurz_2022#10]
Ahoj, s tímto úkolem jsem si nevěděla rady, resp. s touto částí:
"Vytvoř krabicový graf a porovnej rozsah teplot v těchto městech."
Nahrála jsem tedy úkol tak jak je, mimo soutěž, jen jestli bys mi poradil, jak by to mohlo vypadat. Moc děkuji:)

https://github.com/Sunriseee/python_kurz_2022/blob/main/ukol_12.ipynb

**Comment by M-Kovar** [comment]
Ahoj, slavnostní poslední komentář Pythonu 1 přichází... Taky mi ten poslední graf dal trochu zabrat, ale dobral jsem se k následujícímu kódu:

```
# Nacteni dat:
teplota = pandas.read_csv("temperature.csv")
vybrana_mesta = teplota[teplota["City"].isin(["Helsinki","Tokyo","Miami Beach"])]
vybrana_mesta = vybrana_mesta[vybrana_mesta.notna()]

# Matplotlib:
vybrana_mesta.boxplot(by="City", column="AvgTemperature")
plt.show()

# Seaborn:
sns.boxplot(x=vybrana_mesta["City"], y=vybrana_mesta["AvgTemperature"])
plt.show()
```

Vynechal jsem nastavení indexu na City, protože s tím Seaborn nějak odmítal pracovat (asi protože se pak index nechová jako běžný sloupec). Obojí vytvoří pěkné grafíky a díky výběrům sloupce přes `by` a `x`, `y` není potřeba dataframe nijak předem upravovat.

Tady je ještě řešení dobrovolného doplňku, kde se dělaly histogramy platů rozdělené podle města pobočky. Opět můžeme data vybrat a rozdělit díky `column` a `by`:

```
platy = pandas.read_csv("platy_2021_02.csv")
platy = platy.set_index("cislo_zamestnance")
liberec = pandas.read_csv("zam_liberec.csv")
plzen = pandas.read_csv("zam_plzeň.csv")
praha = pandas.read_csv("zam_praha.csv")
liberec["mesto"] = "liberec"
plzen["mesto"] = "plzen"
praha["mesto"] = "praha"
zamestnanci = pandas.concat([liberec, plzen, praha], ignore_index=True)
zamestnanci_platy = zamestnanci.merge(platy)

zamestnanci_platy.hist(column="plat", by="mesto")
plt.title("Platy v jednotlivych mestech")
plt.xlabel("mzda v kc")
plt.ylabel("pocet zamestnancu")
plt.show
```

Tak díky za příjemnou spolupráci během kurzu a ať se daří v pythoních i nepythoních dobrodružstvích:).

**Comment by Sunriseee** [comment]
Omlouvám se že na to koukám až nyní. Každopádně moc děkuji, ten graf mi teda za boha nešel :D
Na ty histogramy jsem asi už pak nějak zapomněla nebo nevím.

Tak ahoj a třeba na shledání na Pythonu 2 :D
