### ISSUE TITLE
Úkol 10

### ISSUE THREAD

**Issue by Sunriseee** [Sunriseee/python_kurz_2022#9]
https://github.com/Sunriseee/python_kurz_2022/blob/main/ukol_10.ipynb

**Comment by M-Kovar** [comment]
Ahoj Hanko, moc pěkné, píšu splněno. Líbí se mi, že jsi výsledky a kód i okomentovala, že sis ověřovala výstupy a použila správný merge, aby nezmizeli zaměstnanci s NaN. Vše je OK, takže jen poznámky k drobnostem:
- Taky mě zaujalo, že má Plzeň vyšší průměrnou mzdu! :D A dokonce i ten Liberec je na tom mírně líp. Mám teorii, že v Praze je centrála, kde jsou zaměstnaní i ne-IT pracovníci jako HR, účetní, atd., kteří mají nižší platy, zatímco na ostatních pobočkách pracují jen megazkušení (takže megadrazí) programátoři, kteří táhnou průměr nahoru. No nic, tohle asi sami nevyřešíme:).
- "ulož je do tabulky" ze zadání hádám znamená "ulož jako DataFrame". Ukládat znova do csv opravdu nedává smysl:).
- K seřazení výsledku groupby: vygooglil jsem metodu `sort_values()`, takže `vykazy.groupby('project')['hours'].sum().sort_values(ascending=False)` krásně funguje.
- K merge bez přejmenování sloupců: Opět vygoogleno, že lze použít argumenty `left_on` a `right_on`, takže `pandas.merge(vykazy, platy2_a_zamestnanci, left_on="emloyee_id", right_on="cislo_zamestnance")` . Blbý je, že v nové tabulce použije zrovna ten levý index s překlepem, což jde vyřešit buď otočením pořadí pravé/levé tabulky nebo dodatečným přejmenováním.
- Poslední úkol, ořezání o některé zaměstnance: Ti, kteří mají NaNy, zase zmizí při merge, tím pádem je zas potřeba vybrat takový způsob merge, který se nám nejvíc hodí.

**Comment by Sunriseee** [comment]
děkuji moc :) je pravda že googlení jsem nakonec moc nedala, vždy jsem naštvala, že jsem našla nějakou blbost či jsem hledala blbě. Takže děkuju že jsi vyhledal něco, co jsem měla vyhledat já :( 👍 Ta sortace s groupem mi přijde jako fakt super!  Díky
